[package]
name = "iassets_poel_demo_j"
version = "1.0.0"

[addresses]
demo_addr = "0xYOUR_ADDR"

[dependencies]
SupraFramework = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir = "aptos-move/framework/supra-framework", rev = "dev" }